<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Answer_model extends CI_Model
{

    public $table = 'answer';
    public $id = 'id_ans';
    public $order = 'DESC';


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id_forum($id_forum)
    {
        $this->db->where('id_forum', $id_forum);
        return $this->db->get($this->table)->result();
    }
    public function insertnew($data){
        $this->db->insert($this->table,$data);
    }

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */