<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Forum_model extends CI_Model
{

    public $table = 'forum';
    public $id = 'id_forum';
    public $order = 'DESC';


    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    public function insertnew($data){
        $this->db->insert($this->table,$data);
    }
    function get_jml_by_id($id)
    {
        $this->db->select('answer');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row()->answer;
    }
    function get_likes_by_id($id)
    {
        $this->db->select('likes');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row()->likes;
    }
    public function update_jml($data,$id_forum){
        $this->db->where('id_forum', $id_forum);
        $this->db->update($this->table, $data); 
    }

}

/* End of file Buku_model.php */
/* Location: ./application/models/Buku_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */