<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
date_default_timezone_set("Asia/Jakarta");
class User extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
        $this->load->library('form_validation');
        $this->db->query("SET time_zone='+7:00'");
        $waktu_sql = $this->db->query("SELECT NOW() AS waktu")->row_array();
        $this->waktu_sql = $waktu_sql['waktu'];
    }

    public function index()
    {
        $user = $this->User_model->get_all();

        $data = array(
            'user_data' => $user
        );

        $this->load->view('inti/header');
        $this->load->view('kelola_user/user_list',$data);
        $this->load->view('inti/footer');
    }

    public function read($id) 
    {
        $row = $this->User_model->get_by_id($id);
        if ($row) {
            $data = array(
    		'username' => $row->username,
        'password' => $row->password,
    		  );
            $this->load->view('inti/header');
            $this->load->view('kelola_user/user_read',$data);
            $this->load->view('inti/footer');
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('user/User'));
        }
    }

     public function delete($id) 
    {
        $row = $this->User_model->get_by_id($id);

        if ($row) {
            $this->User_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('user/User'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('user/User'));
        }
    }
    public function registrasi(){
        $this->load->view('regis');
    }
    public function view_login(){
        $this->load->view('v_login');
    }
    public function insertnew(){
        $data =  array(
            'username' => $this->input->post('username'), 
            'email' => $this->input->post('email'), 
            'password' => $this->input->post('password'), 
            'role' => 'user'
            );
        $this->User_model->insert($data);
        $this->session->set_flashdata('message', 'Success');
        // $this->output->enable_profiler(TRUE);
        redirect(site_url('user/User/view_login'));
    }
    public function login(){
        $pass = $this->input->post('password');
        $data = $this->input->post('email');
        $query=$this->User_model->get_by_email($data);
        if($query->num_rows()>0){
            if($query->row()->password == $pass){
                foreach ($query->result() as $result1) 
                {
                    $sess = array(
                        'email'=>$result1->email,
                        'user_id'=>$result1->id_user,
                        'name' => $result1->username
                        );
                }
                $this->session->set_userdata($sess);
                if($query->row()->role == 'user'){
                    redirect(site_url('materi/Materi/materi_user'));
                } elseif ($query->row()->role == 'admin') {
                    redirect(site_url('Welcome/index'));
                } else {
                    echo "<script>
                    alert('Username atau password yang anda masukkan salah');
                    document.location.href='".site_url('user/User/view_login')."';
                    </script>";
                    break;
                }
            }else{
                echo "<script>
                alert('Username atau password yang anda masukkan salah');
                document.location.href='".site_url('user/User/view_login')."';
                </script>";
                break;
            }
        } else {
            echo "<script>
                alert('Username atau password yang anda masukkan salah');
                document.location.href='".site_url('user/User/view_login')."';
            </script>";
        }

    }
    public function logout(){
        session_destroy();
        redirect('user/User/view_login');
    }
   

  

}

/* End of file Buku.php */
/* Location: ./application/controllers/Buku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-06 11:21:06 */
/* http://harviacode.com */